# Etapa 1: Construcción
FROM node:18 as builder

# Crea el directorio de trabajo
WORKDIR /app

# Copia archivos necesarios
COPY . .

# Instala dependencias
RUN yarn install --frozen-lockfile

# Construye la app
RUN yarn tsc
RUN yarn build:backend --config app-config.yaml

# Etapa 2: Imagen final
FROM node:18-slim

# Crea un usuario no-root
RUN useradd --user-group --create-home --shell /bin/false backstage

# Crea directorio de trabajo
WORKDIR /app

# Copia archivos desde la etapa anterior
COPY --from=builder /app /app

# Cambia propietario por seguridad
RUN chown -R backstage:backstage /app

# Usa usuario seguro
USER backstage

# Expone el puerto por defecto
EXPOSE 7007

# Comando para arrancar el backend
CMD ["node", "packages/backend", "--config", "app-config.yaml"]
