name: Build and Push Docker Image on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Ejecuta en un runner de GitHub (Linux)

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura Docker Buildx (para mejor rendimiento)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login en Docker Hub (requiere credenciales en Secrets)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construye y sube la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Usa el Dockerfile en la raíz
          push: true  # Sube la imagen al registry
          tags: |
            tu-usuario-docker/nombre-app:latest
            tu-usuario-docker/nombre-app:${{ github.sha }}

      # (Opcional) Notificación en Slack/Email
      - name: Notify success
        if: success()
        run: echo "✅ Docker image built and pushed successfully!"
