name: Docker Build & Push

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  docker:
    if: github.event.pull_request.merged == true  # ✅ solo corre si fue merge real
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }} .

      - name: Subir imagen a Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }}
