name: Docker Build & Push

on:
  pull_request:
    types: [closed]
    branches:
      - master  # Usa 'master' o 'main' según tu repo

jobs:
  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Dockerfile
        run: |
          if [ ! -f "Dockerfile" ]; then
            echo "❌ Error: Dockerfile not found in root directory!"
            ls -la
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Tus variables existentes
          password: ${{ secrets.DOCKER_PASSWORD }}  # (asegúrate de que sean correctas)

      - name: Build and Push
        run: |
          # Build with cache and tags
          docker buildx build --push \
            --tag ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest \
            --tag ${{ secrets.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }} 